\getenv app_password EMERADAR_DB_PASSWORD
CREATE ROLE emeradar_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE PASSWORD :'app_password';
CREATE DATABASE emeradar OWNER emeradar_app;
REVOKE CONNECT, TEMPORARY ON DATABASE emeradar FROM PUBLIC;
